<?xml version="1.0"?>
<package format="3">
  <name>aetheris_dummy_sensors</name>
  <version>0.0.1</version>
  <description>Dummy IMU and GPS publishers for testing</description>
  <maintainer email="your@email.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

</package>
